name: Check Archived Repositories

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 UTC
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

jobs:
  check-archives:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For pushing README.md
      actions: read    # For running Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run archive checker
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          python archive_checker.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git pull --rebase origin main
          git add README.md extracted_links.txt archive_checker.log
          git commit -m 'Update README with archived repositories' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ github.token }}
