name: Check Archived Repositories

on:
  schedule:
    - cron: '0 0 * * 0,2,4'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-archives:
    runs-on: macos-latest

    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.1"

      - name: Build archive_bot
        run: swift build -c release

      - name: Run archive_bot
        run: .build/release/archive_bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m 'ci(bot): update archive status table'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
