name: Check Archived Repositories

on:
  schedule:
    - cron: '0 0 * * 0,2,4'  # Sun/Tue/Thu at ~00:00 UTC (±5 mins)
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  check-archives:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run archive checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python archive_checker.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m 'Update README with archived repositories'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
