name: Check Archived Repositories

on:
  schedule:
    - cron: '0 0 * * 0,2,4'
  workflow_dispatch:
  push:
    branches:
      - swift-archive-bot

jobs:
  check-archives:
    runs-on: macos-latest

    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.10"

      - name: Clean Swift build cache
        run: swift package clean

      - name: Build Swift archive bot
        run: swift build -c release

      - name: Run ArchiveDetective
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .build/release/ArchiveDetective

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m 'Update README with archived repositories'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
