name: Check Archived Repositories

on:
  schedule:
    - cron: '0 0 * * 0,2,4'  # Sun/Tue/Thu at ~00:00 UTC (±5 mins)
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  check-archives:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ArchiveDetective
        run: |
          swift build -c release
          .build/release/ArchiveDetective
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m 'Update README with archived repositories'
          git push
